### ISSUE TITLE
conflict in ShowPlayerDialog

### ISSUE THREAD

**Issue by KirovNoName** [f0Re3t/nex-ac_rakcheat#20]
help

error messsage:

![image](https://github.com/user-attachments/assets/882b1a49-3f4f-48fd-8ed9-f65e9e4f1a81)

ShowPlayerDialog conflict

![image](https://github.com/user-attachments/assets/d64b4659-2c19-4db6-b88f-68ef9c346efd)

**Comment by f0Re3t** [comment]
it's warning message, not error
add const correct parameter in anticheat if you use includes with const-correct
